<?php

namespace ServiceJF\ChallengeCIBundle\Repository;

use ServiceJF\CoreBundle\Entity\Season;
use ServiceJF\UserBundle\Entity\User;

/**
 * PointsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserAndSeason(User $user, Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->andWhere('p.season = :season')
            ->setParameters(array(
                'season' => $season,
                'user' => $user
            ))
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAllRankableUsers(Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.total >= 5')
            ->andWhere('p.season = :season')
            ->setParameters(array(
                'season' => $season
            ))
            ->orderBy('p.totalPoints', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getGeneralRanking(Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.total >= 5')
            ->andWhere('p.season = :season')
            ->setParameters(array(
                'season' => $season
            ))
            ->orderBy('p.totalPoints', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
