<?php

namespace ServiceJF\ChallengeCHBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRanking()
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.points', 'DESC')
            ->addOrderBy('p.perfects', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
