<?php

namespace ServiceJF\MiettesBundle\Repository;

/**
 * VolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolunteerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDraw($limit)
    {
        $qb = $this->createQueryBuilder('v');
        $limitDate = new \DateTime();
        $limitDate->modify('-7 days');
        return $qb
            ->where($qb->expr()->orX(
                $qb->expr()->lt('v.lastCleanup',':limitDate'),
                $qb->expr()->isNull('v.lastCleanup')
            ))
            ->andWhere('v.active = 1')
            ->setParameter('limitDate', $limitDate)
            ->orderBy('v.virtualCleanups', 'ASC')
            ->setFirstResult($limit)
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
