<?php

namespace ServiceJF\ChallengeCM18Bundle\Repository;

use ServiceJF\ChallengeCM18Bundle\Entity\Player;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends \Doctrine\ORM\EntityRepository
{
}
