<?php

namespace ServiceJF\ChallengeCM18Bundle\Repository;

/**
 * GamePhaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePhaseRepository extends \Doctrine\ORM\EntityRepository
{
}
