<?php

namespace ServiceJF\ChallengeCM18Bundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRanking()
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.points', 'DESC')
            ->addOrderBy('p.perfect', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findForRankingMail()
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.identity', 'i')
            ->addOrderBy('p.points', 'DESC')
            ->addOrderBy('p.perfect', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
