<?php

namespace ServiceJF\ChallengeFGBundle\Repository;

/**
 * PunchlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PunchlineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFromDate(\DateTimeImmutable $date)
    {
        $date_begin = $date->modify('first day of this month');
        $date_end = $date->modify('last day of this month');
        $date_begin = $date_begin->modify('00:00:00');
        $date_end = $date_end->modify('23:59:59');
        return $this->createQueryBuilder('p')
            ->where('p.postDate BETWEEN :date_begin AND :date_end')
            ->setParameters(array(
                    'date_begin' => $date_begin,
                    'date_end' => $date_end)
            )
            ->andWhere('p.enabled = 1')
            ->orderBy('p.postDate', 'DESC')
            ->leftJoin('p.votes', 'v')
            ->getQuery()
            ->getResult();
    }

}
