<?php

namespace ServiceJF\ChallengeFGBundle\Repository;

use ServiceJF\ChallengeFGBundle\Entity\Punchline;
use ServiceJF\UserBundle\Entity\User;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRemainingVotes(User $user)
    {
        $date_begin = new \DateTime("first day of this month");
        $date_end = new \DateTime("last day of this month");
        $votes = $this->createQueryBuilder('v')
            ->select('COUNT(v)')
            ->where('v.voter = :user')
            ->andWhere('v.voteDate BETWEEN :date_begin AND :date_end')
            ->setParameters(array(
                    'user' => $user,
                    'date_begin' => $date_begin,
                    'date_end' => $date_end)
            )
            ->getQuery()
            ->getSingleScalarResult();
        return 3 - $votes;
    }

}
