<?php

namespace ServiceJF\ChallengeDLBundle\Repository;

/**
 * SetBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetBetRepository extends \Doctrine\ORM\EntityRepository
{
}
