<?php

namespace ServiceJF\ChallengeDLBundle\Repository;

/**
 * ValidBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidBetRepository extends \Doctrine\ORM\EntityRepository
{
}
