<?php

namespace ServiceJF\ChallengeCSSBundle\Repository;

use ServiceJF\CoreBundle\Entity\Season;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGeneralRanking(Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.season = :season')
            ->setParameters(array(
                'season' => $season
            ))
            ->orderBy('p.points', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getPointsRanking(Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.season = :season')
            ->setParameters(array(
                'season' => $season
            ))
            ->orderBy('p.alternativePoints', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getGoalAverageRanking(Season $season)
    {
        return $this->createQueryBuilder('p')
            ->where('p.season = :season')
            ->setParameters(array(
                'season' => $season
            ))
            ->orderBy('p.goalAverage', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
