<?php

namespace ServiceJF\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEnabledUsersByService()
    {
        return $this
            ->createQueryBuilder('u')
            ->orderBy('u.service')
            ->addOrderBy('u.name')
            ->where('u.enabled = true')
            ->getQuery()
            ->getResult();
    }

    public function findDisabledUsersByService()
    {
        return $this
            ->createQueryBuilder('u')
            ->orderBy('u.service')
            ->addOrderBy('u.name')
            ->where('u.enabled = false')
            ->getQuery()
            ->getResult();
    }

    public function findFromService($service_id)
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.service = :service')
            ->orderBy('u.name')
            ->setParameters(array(
                'service' => $service_id
            ));
    }
}
