<?php

namespace ServiceJF\CoreBundle\Repository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate(\DateTime $date) {
        return $this->createQueryBuilder('s')
            ->where(':date BETWEEN s.dateBegin AND s.dateEnd')
            ->setParameters(array(
                'date' => $date
            ))
            ->getQuery()
            ->getSingleResult();
    }
}